github:
	Rscript -e "rmarkdown::render('../Rmarkdown/README.Rmd', encoding = 'UTF-8')"

pdf:
	Rscript -e "rmarkdown::render('../Rmarkdown/README.Rmd', encoding = 'UTF-8', output_format = 'pdf_document')"
