---
title: R Programming 2nd Assignments
author: Sungpil Han
date: "`r Sys.time()`"
output: 
  github_document:
    df_print: kable
bibliography: 'allPackages.bib'
---

## Introduction

한학기 동안 고생 많으셨습니다. 

두번째 과제에 대한 현황을 정리하였습니다. 성공적으로 설치된 R Packages의 목록을 `knitr::write_bib()` [@R-knitr]와 `RefManageR::ReadBib()` [@R-RefManageR]을 사용하여 나타내었습니다. 

제출하셨으나 목록에 자신의 패키지가 보이지 않는 분은 2017-06-21 18:00 이후 shan@acp.kr 로 알려주세요.


```{r setup, include = FALSE}
Path <- './container'
PathArg <- '--library="~/asancpt/Rprogramming/lib/container"'
library(knitr)
library(RefManageR)
```

```{r eval = FALSE, include = FALSE}
# Direct Submission

install.packages("sources/Sunscreen_0.1.0.tar.gz", lib = Path, repos = NULL, type = "source")
install.packages("sources/imageML_0.1.0.tar.gz", lib = Path, repos = NULL, type = "source") # Error
install.packages("sources/MyFunc_1.0.0.tar.gz", lib = Path, repos = NULL, type = "source") 
install.packages("sources/MyUtil_0.1.0.tar.gz", lib = Path, repos = NULL, type = "source") 
install.packages("sources/ECOG_0.1.0.tar.gz", lib = Path, repos = NULL, type = "source")
install.packages("sources/windex_0.1.0.tar.gz", lib = Path, repos = NULL, type = "source")

# Github Submission

devtools::install_github("Eunsol-Lee/Lottery", args = c(PathArg), force = TRUE)
devtools::install_github("shanmdphd/cats", args = c(PathArg), force = TRUE)
devtools::install_github("shanmdphd/glasgowcoma", args = c(PathArg), force = TRUE)
```

```{r include = FALSE}
Packages <- c("Sunscreen", "MyFunc", "MyUtil", "ECOG", "windex",
              "lottery", "cats", "glasgowcoma")
loadPackages <- lapply(Packages, library, character.only = TRUE, lib.loc = Path)
```

```{r include = FALSE}
knitr::write_bib(x = Packages, file = 'RprogrammingPackages.bib')
knitr::write_bib(x = .packages(), file = 'allPackages.bib')
```

## List of Submitted R Packages

`r Sys.time()` 현재

```{r, echo = FALSE, results = 'asis'}
# bibtex::read.bib(file = 'RprogrammingPackages.bib')
print(ReadBib('RprogrammingPackages.bib'), .opts = list(cite.style = "authoryear"))
```


## References
